pipeline {
    agent { node { label 'Agent -1'}}


    stages {
        stage('Init') {
            steps {
                echo 'Initializing......'
                sh'''
                    cd 01-vpc
                    
                    ls -ltr
                    pwd
                    terraform init


                '''
            
            }
        }
        stage('Plan') {
            steps {
                echo 'Planning.......'
                sh'''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform plan

                '''
            }
        }
        stage('Apply') {
            steps {
                echo 'Applying....'
                sh'''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform apply -auto-approve

                '''
                
                
                
            }
        }
    }

    post {
        always {
            echo 'I will always run weather job is success or not'
        }

        success{
            echo 'I will run only when job is success'
            
        }

        failure{
            echo 'I will run when failure'
        }

    }
}